import Footer from '@/components/footer'
import Header from '@/components/header'
import './globals.css'
export const metadata = {
  title: 'Find Affordable Medical Equipment in Pakistan! | Medex Worldwide',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">      
      <body>
      <Header/>
      {children}
      <Footer/>
      </body>      
    </html>
  )
}
