import "./globals.css";
import { ApolloProvider } from "@apollo/client";
import { client } from "@/config/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider client={client}>
        <div>{children}</div>
        <div>side</div>
        </ApolloProvider>
      </body>
    </html>
  );
}
